version: "3.7"

services:
  dis-bot:
    container_name: dis-bot
    # user: "node:node"
    build:
      context: .
      dockerfile: Dockerfile
    image: dis-bot:latest
    # image: vruzhentsov/boys-next-door-dis-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - lavalink
      - mongo

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3-alpine # pin the image version to Lavalink v3
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
    env_file:
      - .env
    volumes:
      - ./lavalink-application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./lava-plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lavalink
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    #ports:
    #  - 2333:2333 # you only need this if you want to make your lavalink accessible from outside of containers

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db:rw
    ports:
      - 27017:27017
    networks:
      - mongo

networks:
  lavalink: # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink
  mongo:
    driver: bridge
