lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:3.2.4"
      repository: "https://maven.topi.wtf/releases"
plugins:
  lavasrc:
    sources:
      spotify: true
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
